# Project 15.2: Project 2 Part 1: Creating a Student Grades Database


### Learning Outcome Addressed

- 5. Create a relational database using Python.


## Index:

- [Question 1](#Question-1)
- [Question 2](#Question-2)
- [Question 3](#Question-3)
- [Question 4](#Question-4)
- [Question 5](#Question-5)
- [Question 6](#Question-6)
- [Question 7](#Question-7)
- [Question 8](#Question-8)
- [Question 9](#Question-9)
- [Question 10](#Question-10)
- [Question 11](#Question-11)
- [Question 12](#Question-12)
- [Question 13](#Question-13)
- [Question 14](#Question-14)
- [Question 15](#Question-15)
- [Question 16](#Question-16)
- [Question 17](#Question-17)
- [Question 18](#Question-18)
- [Question 19](#Question-19)
- [Question 20](#Question-20)




## Question 1

*5 points*

Write a Python *dictionary*, *`s1`*, with *keys, `id`* and `name`, and corresponding values, *`1`* and `Alice`.

Write a Python *dictionary*, *`s2`*, with *keys, `id`* and `name`, and corresponding values, *`2`* and `Bob`.

Write a Python *dictionary*, *`s3`*, with *keys, `id`* and `name`, and corresponding values, *`3`* and `Fred`.

In [1]:
### GRADED

### YOUR SOLUTION HERE
s1 = None
s2 = None
s3 = None

### BEGIN SOLUTION
s1 = {'id': 1, 'name': 'Alice'}
s2 = {'id': 2, 'name': 'Bob'}
s3 = {'id': 3, 'name': 'Fred'}

### END SOLUTION



## Question 2

*5 points*

Define a Python *dictionary*, *`student`*, with *key, `students`*, and corresponding values in a *list* containing the *dictionaries `s1`*, *`s2`*, and *`s3`* as defined in Question 1.


In [2]:
### GRADED

### YOUR SOLUTION HERE
student = None

### BEGIN SOLUTION
student = {'students': [s1, s2, s3]}

### END SOLUTION

## Question 3

*5 points*

Write a Python *dictionary*, *`p1`*, *key, `id`*, `MaxScore`, and corresponding values *`1`* and `100`.

Write a Python *dictionary*, *`p2`*, *key, `id`*, `MaxScore`, and corresponding values *`2`* and `80`.

Write a Python *dictionary*, *`p3`*, *key, `id`*, `MaxScore`, and corresponding values *`3`* and `90`.

In [3]:
### GRADED

### YOUR SOLUTION HERE
p1 = None
p2 = None
p3 = None

### BEGIN SOLUTION
p1 = {'id': 1, 'MaxScore':100}
p2 = {'id': 2, 'MaxScore':80}
p3 = {'id': 3, 'MaxScore':90}

### END SOLUTION

## Question 4

*5 points*

Define a Python *dictionary*, *`psets`*, with *key, `psets`*, and corresponding values in a *list* containing the *dictionaries `p1`*, *`p2`*, and *`p3`* as defined in Question 3.

In [4]:
### GRADED

### YOUR SOLUTION HERE
psets = None

### BEGIN SOLUTION
psets = {'psets': [p1, p2, p3]}

### END SOLUTION

## Question 5

*5 points*

Write a Python *dictionary*, *`g1`*, *key, `sid`*, *`pid`*, `score` and corresponding values *`1`* and `1`, and `90`.

Write a Python *dictionary*, *`g3`*, *key, `sid`*, *`pid`*, `score` and corresponding values *`2`* and `1`, and `95`.

Write a Python *dictionary*, *`g3`*, *key, `sid`*, *`pid`*, `score` and corresponding values *`1`* and `2`, and `50`.

In [5]:
### GRADED

### YOUR SOLUTION HERE
g1 = None
g2 = None
g3 = None

### BEGIN SOLUTION
g1 = {'sid': 1, 'pid':1, 'score':90}
g2 = {'sid': 2, 'pid':1, 'score':95}
g3 = {'sid': 1, 'pid':2, 'score':50}

### END SOLUTION

## Question 6

*5 points*

Define a Python *dictionary*, *`grades`*, with *key, `grades`*, and corresponding values in a *list* containing the *dictionaries `g1`*, *`g2`*, and *`g3`* as defined in Question 5.

In [6]:
### GRADED

### YOUR SOLUTION HERE
grades = None

### BEGIN SOLUTION
grades = {'grades': [g1, g2, g3]}

### END SOLUTION

## Question 7

*5 points*

Define a Python *dictionary*, *`grades`*, with *key, `students`*, *`psets`*, *`grades`*, and corresponding values equal to empty *lists*.

In [7]:
### GRADED

### YOUR SOLUTION HERE
db = None

### BEGIN SOLUTION
db = {'students': [], 'psets': [], 'grades': []}

### END SOLUTION

## Question 8

*5 points*

Define a Python *function*, *`addStudent`*, that takes, as inputs, the database, *`db`*, that was created in Question 7, *`studentID`*, and *`studentName`*.

Your *function* should add a *dictionary* to the database with *keys, `id`* and *`name`*, and corresponding values *`studentId`* and *`studentName`*.



In [8]:
### GRADED

### YOUR SOLUTION HERE
def addStudent():
    pass

### BEGIN SOLUTION
def addStudent(db, studentId, studentName):
    db['students'].append({'id':studentId, 'name':studentName})

### END SOLUTION

Below, you will add information to the *`db`* database about *`s1`*, *`s2`*, and *`s3`* by using the *`addStudent` function* as defined in Question 8.

In [9]:

addStudent(db, 1, 'Alice')
addStudent(db, 2, 'Bob')
addStudent(db, 3, 'Fred')
db

{'students': [{'id': 1, 'name': 'Alice'},
  {'id': 2, 'name': 'Bob'},
  {'id': 3, 'name': 'Fred'}],
 'psets': [],
 'grades': []}

## Question 9

*5 points*

Define a Python *function*, *`addPset`*, that takes, as inputs, the *`db`* database that was created in Question 7, *`pset_id`*, and *`pset_total_points`*.

Your *function* should add to the database a *dictionary* with *keys, `id`* and *`points`*, and corresponding values *`pset_id`* and *`pset_total_points`*.

In [10]:
### GRADED

### YOUR SOLUTION HERE
def addPset():
    pass

### BEGIN SOLUTION
def addPset(db, pset_id, pset_total_points):
    db['psets'].append({'id':pset_id, 'points':pset_total_points})

### END SOLUTION

Below, you will add information to the *`db`* database about *`p1`*, *`p2`*, and *`p3`* by using the *`addPset` function* that was defined in Question 9.

In [11]:
addPset(db, 1, 100)
addPset(db, 2, 90)
addPset(db, 3, 95)
db

{'students': [{'id': 1, 'name': 'Alice'},
  {'id': 2, 'name': 'Bob'},
  {'id': 3, 'name': 'Fred'}],
 'psets': [{'id': 1, 'points': 100},
  {'id': 2, 'points': 90},
  {'id': 3, 'points': 95}],
 'grades': []}

## Question 10

*5 points*

Define a Python *function*, *`addGrade`*, that takes, as inputs, the *`db`* database that was created in Question 7, *`student_id`, `pset_id`*, and *`points`*.

Your *function* should add a *dictionary* to the database with *keys, `student`*, *`pset`*, and *`points`*, and corresponding values *`student_id`*, *`pset_id`*, and *`points`*.

In [12]:
### GRADED

### YOUR SOLUTION HERE
def addGrade():
    pass

### BEGIN SOLUTION
# Record a student's grade on a pset.
def addGrade(db, student_id, pset_id, points):
    db["grades"].append({"student": student_id,
                         "pset": pset_id,
                         "points": points})

### END SOLUTION

Below, you will add information to the *`db`* database about *`g1`*, *`g2`*, and *`g3`* by using the *`addGrade` function* that was defined in Question 10.

In [13]:
addGrade(db, 1, 1, 80)
addGrade(db, 1, 2, 35)
addGrade(db, 1, 3, 95)
addGrade(db, 2, 3, 89)
addGrade(db, 3, 3, 100)


db

{'students': [{'id': 1, 'name': 'Alice'},
  {'id': 2, 'name': 'Bob'},
  {'id': 3, 'name': 'Fred'}],
 'psets': [{'id': 1, 'points': 100},
  {'id': 2, 'points': 90},
  {'id': 3, 'points': 95}],
 'grades': [{'student': 1, 'pset': 1, 'points': 80},
  {'student': 1, 'pset': 2, 'points': 35},
  {'student': 1, 'pset': 3, 'points': 95},
  {'student': 2, 'pset': 3, 'points': 89},
  {'student': 3, 'pset': 3, 'points': 100}]}

## Question 11

*5 points*

Define a Python *function*, *`getGrade`*, that takes, as inputs, the *`db`* database that was created in Question 7, *`student_id`, and `pset_id`*.

 Your *function* should return the grade of the corresponding student id and problem set id.
 
**NOTE:** Use a *list comprehension*.

In [14]:
### GRADED

### YOUR SOLUTION HERE
def getGrade():
    pass

### BEGIN SOLUTION
# Record a student's grade on a pset.
def getGrade(db, student_id, pset_id):
    return [row['points'] for row in db['grades']
           if row['student'] ==student_id and row['pset'] ==pset_id]

### END SOLUTION

Now, verify that the *`getGrade` function* works as expected for the student with student id equal to 1 and problem set id equal to 1.

In [15]:
getGrade(db,1,1)

[80]

## Question 12

*5 points*

Define a Python *function*, *`getGradeDict`*, that takes, as inputs, *`student_id`*, and *`pset_id`*.

Your *function* should return the grade of the corresponding student id and problem set id.
 
**NOTE:** Use a *dictionary comprehension*.

In [16]:
### GRADED

### YOUR SOLUTION HERE
def getGradeDict():
    pass

### BEGIN SOLUTION
def getGradeDict(student_id, pset_id):
    return {"grade": row["points"] for row in db["grades"] 
            if row["student"] == student_id and row["pset"] == pset_id}

### END SOLUTION

Now, verify that the *`getGradeDict` function* works as expected for the student with id equal to 2 and problem set id equal to 3.

In [17]:
print(getGradeDict(2, 3))

{'grade': 89}


## Question 13

*5 points*

Define a Python *function*, *`empty`*, that takes zero arguments as inputs.

Your *function* should return a *dictionary* with *keys, `students`*, *`psets`*, and *`grades`*, and corresponding values equal to empty *dictionaries*.

In [18]:
### GRADED

### YOUR SOLUTION HERE
def empty():
    pass

### BEGIN SOLUTION
def empty():
    return {'students':{}, 'psets':{}, 'grades':{}}
### END SOLUTION

Below, an empty new database is defined for you.

In [19]:
db_dict = empty()

## Question 14

*5 points*

Define a Python *function*, *`addStudentDict`*, that takes, as inputs, *`db`*, *`student_id`*, and *`student_name`*.

Your *function* should add as a value the *key `students`* in the *`db`* *dictionary*. This value will be a *dictionary* with *keys* equal to *`student_id`* and values equal to *`student_name`*.

In [20]:
### GRADED

### YOUR SOLUTION HERE
def addStudentDict():
    pass

### BEGIN SOLUTION
def addStudentDict(db, student_id, student_name):
    db['students'][student_id] = student_name
### END SOLUTION

## Question 15

*5 points*

Define a Python *function*, *`addPsetDict`*, that takes, as inputs, *`db`*, *`pset_id`*, and *`pset_total_points`*.

Your *function* should add as a value the *key `psets`* in the *`db`* *dictionary*. This value will be a *dictionary* with *keys* equal to *`pset_id`* and values equal to *`pset_total_points`*.

In [21]:
### GRADED

### YOUR SOLUTION HERE
def addPsetDict():
    pass

### BEGIN SOLUTION
def addPsetDict(db, pset_id, pset_total_points):
    db['psets'][pset_id] = pset_total_points
### END SOLUTION

## Question 16

*5 points*

Define a Python *function*, *`addGradeDict`*, that takes, as inputs, *`db`*, *`student_id`* *`pset_id`*, and *`points`*.

Your *function* should add as a value the *key `grades`* in the *`db`* *dictionary*. This value is going to be a nested *dictionary* with *keys* equal to *`student_id`* and values equal to a *dictionary* with *keys* equal to *`pset_id`* and values equal to *`points`*.

If the student does not have any grades, your *function* should add an empty value to the  *dictionary* *`db_dict`*.

In [22]:
### GRADED

### YOUR SOLUTION HERE
def addGradeDict():
    pass

### BEGIN SOLUTION
def addGradeDict(db, student_id, pset_id, points):
    if student_id not in db['grades']:
        db['grades'][student_id] = {}
    db['grades'][student_id][pset_id] = points
### END SOLUTION

Now, try to reset your *`db_dict`* *dictionary* and fill it with some values:

In [23]:
addStudentDict(db_dict, 1, "Alice")
addStudentDict(db_dict, 2, "Bob")
addStudentDict(db_dict, 3, "Charlie")
#          pset_id, max_score
addPsetDict(db_dict, 1, 100)
addPsetDict(db_dict, 2, 120)
addPsetDict(db_dict, 3, 130)
#          student_id, pset_id, value
addGradeDict(db_dict, 1, 1, 98)
addGradeDict(db_dict, 1, 2, 108)
addGradeDict(db_dict, 1, 3, 125)
addGradeDict(db_dict, 2, 3, 115)
addGradeDict(db_dict, 3, 3, 110)

print(db_dict)

{'students': {1: 'Alice', 2: 'Bob', 3: 'Charlie'}, 'psets': {1: 100, 2: 120, 3: 130}, 'grades': {1: {1: 98, 2: 108, 3: 125}, 2: {3: 115}, 3: {3: 110}}}


In the code cell below, two *functions, `get()`* and *`get2()`* are defined.

The *`get()` function* takes as input a *dictionary* and a *key*. The *function* returns the *key* if it's present in the *dictionary*. Otherwise, it returns `None`.


The *`get2()` function* takes as input a *dictionary* and two *keys*. The *function* returns the *keys* if they're present in the *dictionary*. Otherwise, it returns `None`.

In [24]:
def get(dict, key):
    if key in dict:
        return dict[key]
    else:
        return None
    
    
    # And a helpful version for traversing nested dictionaries
def get2(dict1, key1, key2):
    dict2 = get(dict1, key1)
    if dict2:
        return get(dict2, key2)
    else:
        return None
    


## Question 17

*5 points*

Define a Python *function*, *`studentGrades`*, that takes, as inputs, *`db`* and *`student_id`*.

Your *function* should return a *dictionary* with *keys* equal to the problem set id and values equal to the grade that the student has gotten for each problem.

For example

```
studentGrades(db_Dict,1)
```

should return

```
{1: 98, 2: 108, 3: 125}
```

**HINT:** Use the *`get()` function* that is defined for you above.

In [25]:
### GRADED

### YOUR SOLUTION HERE
def studentGrades():
    pass

### BEGIN SOLUTION
def studentGrades(db, student_id):
    return get(db["grades"], student_id)
### END SOLUTION

In the code cell below, another helper *function*, the *`gradeOn()` function* is defined.

This *function* takes as input a *dictionary*, the student id, and the problem set id, and it returns the corresponding grade with the help of the *`get2()` function* that is defined above.

Run the code cell below to see how this *function* works.

In [26]:
def gradeOn(db, student_id, pset_id):
    return get2(db["grades"], student_id, pset_id)

gradeOn(db_dict, 1,1)

98

## Question 18

*5 points*

Define a Python *function*, *`gradeOnWeighted`*, that takes, as inputs, *`db`*, *`student_id`, `pset_id`*, and *`pset_points`*. 

Your *function* should return the weighted grade of a student based on grade and the maximum number of points available for that problem based on the formula given below:

$$\text{weighted_grade} = \frac{\text{grade}}{\text{pset_points}}*100$$


If the grade is not available, your *function* should return `None`.

For example

```
gradeOnWeighted(db_dict, 1,2, 120) 
```

should return

```
0.9
```

This makes sense as the student with student id equal to one (Alice) earned 108 out of 120 for the problem set with id equal to 2. Therefore, the weighted grade is equal to 0.9.


**HINT:** Use the *`gradeOn()` function* that is defined above.

In [1]:
### GRADED

### YOUR SOLUTION HERE
def gradeOnWeighted():
    pass

### BEGIN SOLUTION

def gradeOnWeighted(db, student_id, pset_id, pset_points):
    grade = gradeOn(db, student_id, pset_id)
    if grade == None:
        return 0
    else:
        return grade / pset_points *100
### END SOLUTION

## Question 19

*5 points*

Define a Python *function*, *`studentGradesWeighted`*, that takes, as inputs, *`db`* and *`student_id`*.

Your *function* should return a *list* with all the weighted grades of a student.

For example

```
studentGradesWeighted(db_dict, 1)
```

should return

```
[98.0, 90.0, 96.15384615384616]
```


**HINT:** Use the *`gradeOnWeighted()` function* that you defined in the previous question to help you *loop* over all the grades of a certain student.

In [28]:
### GRADED

### YOUR SOLUTION HERE
def studentGradesWeighted():
    pass

### BEGIN SOLUTION
def studentGradesWeighted(db, student_id):
    return [gradeOnWeighted(db, student_id, pset_id, pset_points)
            for pset_id, pset_points in db["psets"].items()]
### END SOLUTION

Finally, a *function*, *`finalGradeOf()` function*, is defined that takes, as input, a *dictionary* and a student id. This *function* will compute and return the final grade of a student.

In [30]:
def finalGradeOf(db, student_id):
    grades = studentGradesWeighted(db, student_id)
    return round(sum(grades) / len(grades) * 100, 1)

finalGradeOf(db_dict, 1)

94.7

## Question 20

*5 points*

Define a Python *function*, *`finalGrades`*, that takes, as input, the *`db` dictionary*.

Your *function* should return a *list* with *dictionaries* as elements. Each *dictionary* will have *keys* equal to *`id`, `name`*, and *`grade`* and corresponding values equal to the student id, the name of the student, and their final grade computed with the help of the *`finalGradeOf()` function* that is defined above.

If your *function* is defined correctly, based on entries in your database,

```
print(finalGrades(db_dict))
```

should return

```
[{'id': 1, 'name': 'Alice', 'grade': 94.7}, {'id': 2, 'name': 'Bob', 'grade': 29.5}, {'id': 3, 'name': 'Charlie', 'grade': 28.2}].
```

In [31]:
### GRADED

### YOUR SOLUTION HERE
def finalGrades():
    pass

### BEGIN SOLUTION
def finalGrades(db):
    return [{"id": id,
             "name": name,
             "grade": finalGradeOf(db, id)}
            for id, name in db["students"].items()]
### END SOLUTION
